name: Repositories and diff history
on:
  # Schedule updates (At minute 0 past every 12th hour)
  schedule: [{ cron: "0 */12 * * *" }]
  # Lines below let you run workflow manually with each commit
  workflow_dispatch:
  push: { branches: ["master", "main", "metrics"] }
jobs:
  # https://github.com/lowlighter/metrics/blob/master/source/plugins/followup/README.md
  follow-up-pr-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.lines.history.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_lines: yes
          plugin_lines_delay: 30
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 2
          plugin_lines_history_limit: 1
          repositories_skipped: |
            @use.patterns
            */*
            +lowlighter/metrics
